export default function () {
  return [
    {
      id : 1,
      firstName : "Till",
      lastName : "Lindemann",
      dateOfBirth : "04.01.1963",
      placeOfBirth : "Leipzig",
      image : "https://wallsdesk.com/wp-content/uploads/2016/12/Till-Lindemann-Background-.jpg", 
      generalInformation : "the son of poet Werner Lindemann and journalist Brigitte Hildegard Lindemann, who worked for Norddeutscher Rundfunk from 1992 until her retirement in 2002. His parents first met at a conference in Bitterfeld in 1959. He grew up in Wendisch-Rambow alongside his younger sister, Saskia. At age 11, he went to a sports school at the Empor Rostock Sport Club, and attended a boarding school from 1977 to 1980. His parents lived separately for career reasons after 1975, and divorced when Lindemann was still young.He lived with his father for a short time, but the relationship was unhealthy; in the book Mike Oldfield im Schaukelstuhl, his father wrote about his own problems with alcoholism and the difficulties of being a father to a teenage Lindemann. In 1978, Lindemann participated in the European Junior Swimming Championships in Florence, finishing 11th in the 1500 m freestyle and 7th in the 400 m freestyle. He was shortlisted to go to the 1980 Olympics in Moscow, but left the sport due to an injury.He later worked as an apprentice carpenter, a gallery technician, a peat cutter, and a basket weaver.",
      imageA : "https://wallsdesk.com/wp-content/uploads/2016/12/Till-Lindemann-High-Quality-Wallpapers.jpg",
      additinalInfo : "Lindemann started to play drums for First Arsch: a play on words perhaps meant to distract the authorities. It was a Schwerin-based punk band. They made an album titled Saddle Up. Till Lindemann also played one song with a German punk band called Feeling B. A song called Lied von der unruhevollen Jugend (<Song of the restless youth>) is credited on the album called Hea Hoa Hoa Hea Hea Hoa (1990) saying Till, Paul H. Landers and Christian <Flake> Lorenz all played on the song Lied von der unruhevollen Jugend. Feeling B was the former band of Paul H. Landers and Christian <Flake> Lorenz. Later in the 1990s, Lindemann began to write lyrics, possibly based on phrases and words from poems that he was beginning to write. He says he <used to drum in a punk band that consisted of bass and drums. We used to work with guest-guitarists, usually Paul and Richard. We did a short tour where I changed instruments with the bassist in the encore, that was such a success, that Richard insisted on starting a project in which I would sing. Other people joined the band but only when I left Schwerin for Berlin did it take serious form.> In 1994, they entered and won a contest in Berlin that allowed them to record a four track demo professionally. Lindemann moved to Berlin. Paul H. Landers formally joined the band, followed by the last member to join, Christian <Flake> Lorenz. Subsequently, in November 2002 Lindemann's own project, the poetry book Messer, was published. It consists of 54 poems compiled by Gert Hof, who is author of the book Rammstein and has been the band's pyrodesigner for the last seven years. "
    },
    {
      id : 2,
      firstName : "Richard",
      lastName : "Kruspe",
      dateOfBirth : "24.06.1967",
      placeOfBirth : "Wittenberg",
      image : "https://i.pinimg.com/originals/3b/d7/e6/3bd7e62663cd8d90632a574330f89302.jpg",
      generalInformation : "He has an younger sister and an older brother. His parents divorced when he was 12. His mother remarried on american, but he did not get along with his stepfather. They moved to the village of Weisen when he was young. As a child, Kruspe was a fan of Kiss. According to him, <KISS represented capitalism in its purest sense, and every child was KISS-infected because they were so big. Kids wrote KISS on their notebooks, and if the teachers saw it, they could get kicked out of school just for having it written on their books.> When he was twelve, he had a KISS poster in his room, but his stepfather tore it down and destroyed it, and Kruspe stayed up all night putting it back together. Kruspe was a wrestler when he was a teenager, but hasn't wrestled for many years, although he did wrestle his twin in the video for Mein Teil.",
      imageA : "https://i2.wp.com/sova.ponominalu.ru/wp-content/uploads/2018/11/ruspe.jpg?fit=1280%2C720&ssl=1",
      additinalInfo : "Rammstein was founded by Kruspe. In 1989, he escaped from East Germany via the border between Austria and Hungary. He went to West Berlin and started a band in 1991, Orgasm Death Gimmicks. At that time, he was very influenced by American music. After the wall came down, he moved back home to Schwerin, where Till Lindemann worked as a basket weaver and played drums in the band First Arsch. At this time, Kruspe lived with Oliver <Ollie> Riedel (of the band The Inchtabokatables) and Christoph <Doom> Schneider (of Die Firma). Richard realized that the music he had previously made was not right for him. He envisioned something with machines and hard guitars together. The three started working together on a new project. Kruspe soon found it hard to write music and lyrics at the same time. He got Till to join them as he had often heard him singing while working. A contest for new bands was announced and the prize was studio time. The four of them recorded the first Rammstein demo and won. Paul H. Landers knew them all and wanted to know what they were doing. After listening, he agreed to join. At this point, all they needed for the machine-sound was a keyboarder. They tried to get Christian <Flake> Lorenz to join, as he had played with Paul before in the band Feeling B. Flake was not entirely thrilled with the idea at first and didn't want to join for a long time. But, he eventually agreed. About the time the band was formed, they all had relationship problems which provided the foundation for their debut album, Herzeleid (Heartache), in 1995. Since then, they have reached gold and platinum status for their music and have become Germany's number one music export."
    },
    {
      id : 3,
      firstName : "Paul",
      lastName : "Landers",
      dateOfBirth : "09.12.1964",
      placeOfBirth : "Berlin",
      image : "https://i.pinimg.com/originals/04/f1/52/04f152fd1b9bd6500523d06bbaa8f03d.jpg",
      generalInformation : "His father is a German man born in Czechoslovakia who taught Slavish languages. His mother is Polish and taught Russian in College. As a child, Paul had health problems and had to start a cure at 6. His nurses even nicknamed him <Kundi> (which can be translated into <regular patient>). At school he was a dreamy-looking boy with large rings under his eyes, not very keen on washing, which often led his teachers to tell him off. When he was 9 his family moved to Moscow where they stayed for one year. It's then that he spent his worst vacation ever, near the Sea of Azov - it used to be part of the USSR, now it is located in the Ukraine. Apart from those holidays, Paul really enjoyed his life in the USSR, even considered Moscow as his home for a little while, and still likes Russia very much. Around 12 or 13 Paul was encouraged to learn the piano like his sister and his parents sent him to private lessons. But very early he gave up the piano for the clarinet. He remembers his clarinet teacher very well mainly because he's the man who taught him how to…take a shower! Paul then started to play the guitar without real dedication – his father had a guitar and taught him only one song, <Wer kann die Lieder der Freiheit verbieten>. Only when Paul was 16, he bought his own Iris e-guitar. Later he learnt the drums by himself and used to practice on Till's. As a teenager Paul used to listen to Jean-Michel Jarre and Klaus Schulze and even tried to be a fan of the Puhdys mainly because all his friends thought that that band was <making shit> (in the derogatory sense of the term). Nonetheless, Paul also remarked once that he had never been able to be a fan of anybody. After his parents' divorce (around the late 1970s) Paul stayed at his mother's until his marriage in 1984. When he was 19 he however tried to live with his father but after 14 days of the latter's routine, Paul realised that he could not cope with it and went back to his mother's before moving in his own flat with his wife.",
      imageA : "https://i.pinimg.com/originals/a4/3b/df/a43bdff504ab79ee31be048ef56115ed.jpg",
      additinalInfo : "Landers is a self-taught guitarist. He can also play the piano and violin, which he learned as a child. Paul plays two Music Man Van Halen guitars and according to the Live Aus Berlin DVD Trivia Game; in his guitar-rack there is a Tech 21 PSA-1 preamp, of which he only uses one preset; he goes from the preamp to the mixer and into a Mesa/Boogie Strategy 500 power amp and two Marshall 4x12 cabinets. When playing in C tuning, Paul uses a Custom Les Paul Studio. During the Völkerball performance of the song <Rammstein>, Paul is seen using another Custom Les Paul Studio which was drop D tuned for the song. He also uses EMG 60 and EMG 81 pickups."
    },
    {
      id : 4,
      firstName : "Christoph",
      lastName : "Schneider",
      dateOfBirth : "11.05.1966",
      placeOfBirth : "Pankov",
      image : "https://magazynperkusista.pl/i/images/6/8/2/cT04MCZ3YWM9Nzc5eDEuNjgyNTA1Mzk5NTY4_src_14682-Christoph-Schneider1.jpg",
      generalInformation : "has six siblings. His interest in playing music started at school, where he played the trumpet. His brother gave him a drum set made of aluminum cans when Christoph was 14, sparking an interest in drums and a dream of being a musician. Schneider left high school at age 16 and went to work as a telecommunications assistant. In 1984, he served his national service with the East German Army; He and Till Lindemann are the only ones to have served in the army out of all of the Rammstein members.",
      imageA : "https://www.laut.de/Rammstein/Fotogalerien/Gelsenkirchen,-Veltins-Arena,-2019-6631/rammstein-gelsenkirchen-veltins-arena-2019-christoph-schneider-201217.jpg",
      additinalInfo : "In 1985, Schneider quit his telecommunication job to pursue his musical ambitions by studying music at university, but failed to get into university twice. His father disapproved of Schneider's learning to play the drums, preferring the trumpet. Schneider tried consistently from 1985 until 1990 to get into bands as a drummer, finally being successful with Die Firma. In 1994, he joined Richard Kruspe and Oliver Riedel in forming an early version of Rammstein. After Till Lindemann joined the band, they entered the Berlin Senate Metrobeat contest, winning the chance to record a professional demo with four tracks. A previous band of Schneider's, Feeling B, provided two other members of Rammstein, Paul Landers and keyboardist Christian Lorenz."
    },
    {
      id : 5,
      firstName : "Oliver ",
      lastName : "Riedel",
      dateOfBirth : "11.04.1971",
      placeOfBirth : "Schwerin",
      image : "https://live.staticflickr.com/5477/10943081783_5c3dc6c089_b.jpg",
      generalInformation : "Growing up, he had relatively good relationships with both of his parents. He attributes this to the small gap between their ages. As a child, he was not a good student, but he made his way through school with the assistance of his mother. Riedel was quite shy, especially during his teenage years; while his friends partied, he would often be found just <hanging around>.",
      imageA : "https://kubnews.ru/upload/iblock/12b/12b5eba820095792f53fa59b421999df.jpg",
      additinalInfo : "In 1990, at the age of nineteen, Oliver began playing in a folk-fiddle/punk-rock band called The Inchtabokatables. In 1994, Riedel, Till Lindemann, Richard Z. Kruspe, and Christoph <Doom< Schneider entered and won the Berlin Senate Metro beat contest that allowed them to record a four track demo professionally. Paul H. Landers and Christian <Flake> Lorenz would later join the band they named Rammstein. The six released their first album, Herzeleid (Heartache) in September, 1995. Their second album, Sehnsucht (Longing) was released in 1997, which would later become platinum. In April 2001, the album Mutter (Mother) was released and a European tour followed, ending on July 13, 2002. It has been reported that at this time the members of Rammstein were seriously discussing whether to continue or not in their present form. It was decided that they should all take some time off and then reconsider whether to continue. In 2003, Rammstein started work on the fourth album, which was to prove a turning point in Rammstein's sound and maturity. September 2004 saw the fruits of this work in the release of Reise, Reise (<Journey, Journey>)."
    },
    {
      id : 6,
      firstName : "Christian Flake",
      lastName : "Lorenz",
      dateOfBirth : "16.11.1966",
      placeOfBirth : "Berlin",
      image : "https://pbs.twimg.com/media/EDttHx4XYAEuaRW.jpg",
      generalInformation : "He chose to play the piano because a childhood friend of his played from the age of three. His parents sent him to a music school, where he said he <began by painting the keys on a window ledge> and <practiced one-half-year on the window ledge>.His parents bought him a piano for one hundred East German marks for his 15th birthday.Lorenz became <addicted> to rock and roll as a boy. He stopped his lessons in order to play with his father's jazz records. <When I joined my first band>, Flake has said, <I noticed that I couldn't play modern music. I still can't!>. At the age of sixteen, he apprenticed as a toolmaker.He has a brother who is four years older.",
      imageA : "https://i.pinimg.com/originals/46/a3/a3/46a3a3b736da629dc1e706f4a4f14511.jpg",
      additinalInfo : "In 1994, Till Lindemann, Richard Z. Kruspe, Oliver <Ollie> Riedel and Christoph <Doom> Schneider entered and won the Berlin Senate Metro beat contest that allowed them to professionally record a four track demo. Paul H. Landers formally joined the band, then finally Flake. He was initially reluctant to join his five bandmates and had to be pestered into becoming a member of Rammstein, as he thought they would be too boring. Eventually, he agreed to join, and the group began work their first album, Herzeleid (Heartache). In the band's performances and videos, Flake is often cast as the outsider of the group, possibly due to his relatively unusual presence as a keyboard player in a heavy metal group. This varies from playing the part of a scientific genius, aloof from the rest of the group, to playing a gimp role, to being left alone at the end of the <Keine Lust> video, and being bullied by the rest of the band, particularly Lindemann. These distinctive roles in the band's theatrical presentation have led to him becoming a very popular member of the group among fans. Flake is probably best known for his part in the controversial live performance of the song <Bück dich> (<Bend down> or <Bend over>), where he and vocalist Till Lindemann engaged in simulated sodomy with a liquor-squirting dildo. On September 23, 1998, in Worcester, Massachusetts (USA) Lindemann and Flake Lorenz were arrested and charged with lewd and lascivious behavior. A statement from Sergeant Thomas Radula of the Worcester Police Department stated that Lindemann was simulating sex with Flake onstage <using a phallic object that shot water over the crowd>. They were held and released the following day on $25 bail. After months of legal debate, they were eventually fined $100."
    },
  ]
}